apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-calculator
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmi-calculator
  template:
    metadata:
      labels:
        app: bmi-calculator
    spec:
      containers:
      - name: bmi-calculator
        image: <your-dockerhub-username>/bmi-calculator:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"